export const clients = [
  {
    id: 'client1',
    name: 'Fashionista Boutique',
    email: 'contact@fashionista.com',
    phone: '+1234567890',
    company: 'Fashionista Boutique',
    address: '123 Fashion St, New York, NY',
  },
  {
    id: 'client2',
    name: 'Style Hub',
    email: 'info@stylehub.com',
    phone: '+0987654321',
    company: 'Style Hub',
    address: '456 Trendy Ave, Los Angeles, CA',
  },
  {
    id: 'client3',
    name: 'Urban Trends',
    email: 'hello@urbantrends.com',
    phone: '+1122334455',
    company: 'Urban Trends Inc.',
    address: '789 Modern Blvd, Chicago, IL',
  },
  {
    id: 'client4',
    name: 'Glamour Lane',
    email: 'sales@glamourlane.com',
    phone: '+1987654321',
    company: 'Glamour Lane',
    address: '321 Chic St, Miami, FL',
  },
  {
    id: 'client5',
    name: 'Vogue Vibes',
    email: 'support@voguevibes.com',
    phone: '+14155552671',
    company: 'Vogue Vibes LLC',
    address: '654 Couture Rd, Dallas, TX',
  },
  {
    id: 'client6',
    name: 'Elegant Attire',
    email: 'contact@elegantattire.com',
    phone: '+17185551234',
    company: 'Elegant Attire',
    address: '987 Fashion Blvd, Atlanta, GA',
  },
  {
    id: 'client7',
    name: 'Chic & Co.',
    email: 'hello@chicandco.com',
    phone: '+16175559876',
    company: 'Chic & Co.',
    address: '222 Glam St, San Francisco, CA',
  },
  {
    id: 'client8',
    name: 'Trendy Threads',
    email: 'info@trendythreads.com',
    phone: '+19175550123',
    company: 'Trendy Threads',
    address: '555 Stylish Ave, Seattle, WA',
  },
  {
    id: 'client9',
    name: 'Runway Ready',
    email: 'sales@runwayready.com',
    phone: '+18185557654',
    company: 'Runway Ready',
    address: '888 Catwalk Rd, Las Vegas, NV',
  },
  {
    id: 'client10',
    name: 'Couture Corner',
    email: 'support@couturecorner.com',
    phone: '+13015553456',
    company: 'Couture Corner',
    address: '777 Designer St, Houston, TX',
  },
  {
    id: 'client11',
    name: 'Mode Makers',
    email: 'contact@modemakers.com',
    phone: '+15015557890',
    company: 'Mode Makers',
    address: '444 Trendy Blvd, Boston, MA',
  },
  {
    id: 'client12',
    name: 'Haute House',
    email: 'hello@hautehouse.com',
    phone: '+17015550987',
    company: 'Haute House',
    address: '333 Luxury Ln, Orlando, FL',
  },
  {
    id: 'client13',
    name: 'Fashion Forward',
    email: 'info@fashionforward.com',
    phone: '+12015556789',
    company: 'Fashion Forward',
    address: '999 Couture Blvd, Phoenix, AZ',
  },
  {
    id: 'client14',
    name: 'Style Squad',
    email: 'support@stylesquad.com',
    phone: '+16015554321',
    company: 'Style Squad',
    address: '101 Chic Ave, Denver, CO',
  },
  {
    id: 'client15',
    name: 'The Wardrobe Co.',
    email: 'sales@wardrobeco.com',
    phone: '+11015553421',
    company: 'The Wardrobe Co.',
    address: '202 Fashion St, Portland, OR',
  },
  {
    id: 'client16',
    name: 'Catwalk Creations',
    email: 'hello@catwalkcreations.com',
    phone: '+15015552345',
    company: 'Catwalk Creations',
    address: '303 Style Rd, Charlotte, NC',
  },
  {
    id: 'client17',
    name: 'Glam Central',
    email: 'contact@glamcentral.com',
    phone: '+18015557654',
    company: 'Glam Central',
    address: '404 Glitz Blvd, Tampa, FL',
  },
  {
    id: 'client18',
    name: 'Threads & Trends',
    email: 'info@threadsandtrends.com',
    phone: '+19015551234',
    company: 'Threads & Trends',
    address: '505 Trendy St, Minneapolis, MN',
  },
  {
    id: 'client19',
    name: 'Runway Luxe',
    email: 'support@runwayluxe.com',
    phone: '+17015556789',
    company: 'Runway Luxe',
    address: '606 Luxe Ave, Nashville, TN',
  },
  {
    id: 'client20',
    name: 'Elite Ensembles',
    email: 'sales@eliteensembles.com',
    phone: '+16015557654',
    company: 'Elite Ensembles',
    address: '707 Elegant Rd, San Diego, CA',
  }
];
