export const items = [
  {
    id: 'item1',
    name: 'Summer Dress',
    description: 'A stylish summer dress perfect for any occasion.',
    price: 49.99,
    stock: 120,
    imageUrl: 'https://source.unsplash.com/400x400/?summer,dress,fashion',
  },
  {
    id: 'item2',
    name: 'Leather Jacket',
    description: 'Premium leather jacket for a bold look.',
    price: 199.99,
    stock: 50,
    imageUrl: 'https://source.unsplash.com/400x400/?leather,jacket,fashion',
  },
  {
    id: 'item3',
    name: 'Casual Sneakers',
    description: 'Comfortable sneakers for everyday wear.',
    price: 79.99,
    stock: 200,
    imageUrl: 'https://source.unsplash.com/400x400/?sneakers,shoes,fashion',
  },
  {
    id: 'item4',
    name: 'Silk Scarf',
    description: 'Elegant silk scarf to elevate your style.',
    price: 29.99,
    stock: 150,
    imageUrl: 'https://source.unsplash.com/400x400/?silk,scarf,fashion',
  },
  {
    id: 'item5',
    name: 'Denim Jeans',
    description: 'Classic blue denim jeans with a modern fit.',
    price: 59.99,
    stock: 180,
    imageUrl: 'https://source.unsplash.com/400x400/?denim,jeans,fashion',
  },
  {
    id: 'item6',
    name: 'Wool Sweater',
    description: 'Cozy wool sweater for cold days.',
    price: 89.99,
    stock: 90,
    imageUrl: 'https://source.unsplash.com/400x400/?wool,sweater,fashion',
  },
  {
    id: 'item7',
    name: 'Evening Gown',
    description: 'Stunning evening gown for special occasions.',
    price: 299.99,
    stock: 25,
    imageUrl: 'https://source.unsplash.com/400x400/?evening,gown,fashion',
  },
  {
    id: 'item8',
    name: 'Baseball Cap',
    description: 'Casual cap to keep you cool and stylish.',
    price: 19.99,
    stock: 300,
    imageUrl: 'https://source.unsplash.com/400x400/?baseball,cap,fashion',
  },
  {
    id: 'item9',
    name: 'Formal Shirt',
    description: 'Crisp formal shirt for office or events.',
    price: 39.99,
    stock: 140,
    imageUrl: 'https://source.unsplash.com/400x400/?formal,shirt,fashion',
  },
  {
    id: 'item10',
    name: 'Wristwatch',
    description: 'Elegant wristwatch with leather strap.',
    price: 149.99,
    stock: 70,
    imageUrl: 'https://source.unsplash.com/400x400/?wristwatch,watch,fashion',
  },
  {
    id: 'item11',
    name: 'Backpack',
    description: 'Durable backpack for travel and daily use.',
    price: 89.99,
    stock: 110,
    imageUrl: 'https://source.unsplash.com/400x400/?backpack,bag,fashion',
  },
  {
    id: 'item12',
    name: 'Sunglasses',
    description: 'Trendy sunglasses with UV protection.',
    price: 24.99,
    stock: 250,
    imageUrl: 'https://source.unsplash.com/400x400/?sunglasses,fashion',
  },
  {
    id: 'item13',
    name: 'Running Shoes',
    description: 'Lightweight running shoes for maximum comfort.',
    price: 99.99,
    stock: 130,
    imageUrl: 'https://source.unsplash.com/400x400/?running,shoes,fashion',
  },
  {
    id: 'item14',
    name: 'Trench Coat',
    description: 'Classic trench coat for a sophisticated look.',
    price: 249.99,
    stock: 60,
    imageUrl: 'https://source.unsplash.com/400x400/?trench,coat,fashion',
  },
  {
    id: 'item15',
    name: 'Handbag',
    description: 'Stylish leather handbag for all occasions.',
    price: 129.99,
    stock: 85,
    imageUrl: 'https://source.unsplash.com/400x400/?handbag,bag,fashion',
  },
  {
    id: 'item16',
    name: 'Beanie',
    description: 'Warm beanie for winter.',
    price: 14.99,
    stock: 220,
    imageUrl: 'https://source.unsplash.com/400x400/?beanie,hat,fashion',
  },
  {
    id: 'item17',
    name: 'Blazer',
    description: 'Tailored blazer for a sharp appearance.',
    price: 179.99,
    stock: 75,
    imageUrl: 'https://source.unsplash.com/400x400/?blazer,jacket,fashion',
  },
  {
    id: 'item18',
    name: 'Yoga Pants',
    description: 'Comfortable and flexible yoga pants.',
    price: 39.99,
    stock: 160,
    imageUrl: 'https://source.unsplash.com/400x400/?yoga,pants,fashion',
  },
  {
    id: 'item19',
    name: 'Cardigan',
    description: 'Soft cardigan for a cozy feel.',
    price: 54.99,
    stock: 100,
    imageUrl: 'https://source.unsplash.com/400x400/?cardigan,sweater,fashion',
  },
  {
    id: 'item20',
    name: 'Ankle Boots',
    description: 'Chic ankle boots for a fashionable step.',
    price: 139.99,
    stock: 65,
    imageUrl: 'https://source.unsplash.com/400x400/?ankle,boots,fashion',
  }
];
